'use client';

import { useState, useRef, useEffect, useCallback } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';

import { classifyStage, sc, objConfig, getShape, getRW, getBinConfig, getTLP } from '@/lib/auditor/classify';
import { fmt } from '@/lib/auditor/format';
import { buildPoolRows, detectPoolType } from '@/lib/auditor/pools';
import { estSlippage, calcFragScore, calcRoutingScore } from '@/lib/auditor/scores';
import { auditAnalysis } from '@/lib/auditor/analysis';
import { buildRiskSection } from '@/lib/auditor/risk';
import { buildMicroCapSection, buildMicroCapTable } from '@/lib/auditor/microcap';
import { buildDonutChart } from '@/lib/auditor/chart';
import { loadLPOwnershipSection } from '@/lib/auditor/ownership';

export default function AuditorClient() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [addr, setAddr] = useState(searchParams.get('addr') || '');
  const [objective, setObjective] = useState('fee');
  const [loading, setLoading] = useState(false);
  const [outputHTML, setOutputHTML] = useState('');
  const outputRef = useRef<HTMLDivElement>(null);

  const lastAuditDataRef = useRef<any>(null);
  const lastAuditAddrRef = useRef('');
  const microCapParamsRef = useRef<{ mc: number; volLiq: number; tvl: number; ref: number } | null>(null);

  // Expose window functions for onclick handlers inside dangerouslySetInnerHTML
  useEffect(() => {
    if (typeof window === 'undefined') return;

    const w = window as any;
    if (!w._dynamo) w._dynamo = {};

    w._dynamo.setMicroCapRef = (ref: number, el: HTMLElement) => {
      if (!microCapParamsRef.current) return;
      microCapParamsRef.current.ref = ref;
      el.closest('div')?.querySelectorAll('.disc-btn').forEach(b => b.classList.remove('primary'));
      el.classList.add('primary');
      const tbl = document.getElementById('micro-cap-table');
      if (tbl) {
        const { mc, volLiq, tvl } = microCapParamsRef.current;
        tbl.innerHTML = buildMicroCapTable(mc, volLiq, tvl, ref);
      }
    };

    w._dynamo.exportMarkdown = () => {
      const d = lastAuditDataRef.current;
      if (!d) return;
      const cfg = objConfig(d.objective);
      const lines = [
        `# Liquidity Audit: ${d.name} (${d.symbol})`,
        `**Address:** \`${d.address}\`  `,
        `**Objective:** ${cfg.label}  `,
        `**Generated:** ${new Date().toLocaleString()}`,
        '',
        '## Key Metrics',
        '| Metric | Value |',
        '|---|---|',
        `| Price | $${d.price.toPrecision(4)} |`,
        `| Market Cap | ${fmt(d.mc)} |`,
        `| Total TVL | ${fmt(d.tvl)} |`,
        `| Vol 24h | ${fmt(d.vol24)} |`,
        `| Liq Ratio | ${d.liqRatio.toFixed(1)}% |`,
        `| Est. Daily Fees | ${fmt(d.estFees)} |`,
        `| Stage | ${d.stage.stage}: ${d.stage.label} |`,
        `| Volatility | ${d.vola} |`,
        '',
        '## Pool Inventory',
        '| DEX | Type | TVL | Vol 24h | Util | 24h Δ |',
        '|---|---|---|---|---|---|',
        ...d.pairs.slice(0, 12).map((p: any) => {
          const tv = parseFloat(p.liquidity?.usd || 0);
          const vo = parseFloat(p.volume?.h24 || 0);
          const ut = tv > 0 ? (vo / tv * 100).toFixed(0) + '%' : '—';
          const ch = p.priceChange?.h24 ?? null;
          const pt = detectPoolType(p);
          return `| ${p.dexId || '?'} | ${pt.type} | ${fmt(tv)} | ${fmt(vo)} | ${ut} | ${ch === null ? '—' : (ch >= 0 ? '+' : '') + ch.toFixed(1) + '%'} |`;
        }),
        '',
        `## Analysis (${cfg.label} Objective)`,
        ...d.paras.map((p: string, i: number) =>
          `### ${['Liquidity Health', 'Pool Structure', 'DLMM Recommendation', 'Action Items'][i] || 'Section ' + (i + 1)}\n${p.replace(/<[^>]+>/g, '')}`
        ),
        '',
        '---',
        '*Generated by Dynamo — Solana Liquidity Terminal*',
      ];
      const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `${d.symbol}-liquidity-audit-${Date.now()}.md`;
      a.click(); URL.revokeObjectURL(url);
    };

    w._dynamo.exportCSV = () => {
      const d = lastAuditDataRef.current;
      if (!d) return;
      const rows: string[][] = [['DEX', 'Type', 'TVL', 'Vol24h', 'Fees24h', 'Utilization', 'PriceChange24h', 'PairAddress']];
      d.pairs.slice(0, 12).forEach((p: any) => {
        const tv = parseFloat(p.liquidity?.usd || 0);
        const vo = parseFloat(p.volume?.h24 || 0);
        const pt = detectPoolType(p);
        rows.push([p.dexId || '', pt.type, tv.toFixed(2), vo.toFixed(2), (vo * 0.003).toFixed(2), tv > 0 ? (vo / tv * 100).toFixed(1) + '%' : '—', p.priceChange?.h24 ?? '', p.pairAddress || '']);
      });
      const csv = rows.map(r => r.map(v => `"${v}"`).join(',')).join('\n');
      const blob = new Blob([csv], { type: 'text/csv' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `${d.symbol}-pools-${Date.now()}.csv`;
      a.click(); URL.revokeObjectURL(url);
    };

    w._dynamo.exportPrint = () => {
      const d = lastAuditDataRef.current;
      if (!d) return;
      const cfg = objConfig(d.objective);
      const s = d.stage;
      const c = sc(s.stage);
      const now = new Date();
      const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
      const lrColor = d.liqRatio < 2 ? '#c0392b' : d.liqRatio < 5 ? '#d35400' : d.liqRatio > 15 ? '#0e7c57' : '#1a6b4a';
      const priceColor = d.priceChg >= 0 ? '#0e7c57' : '#c0392b';
      const sectionTitles = ['Liquidity Health Assessment', 'Pool Structure & Fragmentation', 'DLMM Configuration Recommendation', 'Recommended Actions'];
      const cfgColor = cfg.color;

      const pdfPoolRows = d.pairs.slice(0, 12).map((p: any) => {
        const tv = parseFloat(p.liquidity?.usd || 0);
        const vo = parseFloat(p.volume?.h24 || 0);
        const fe = vo * 0.003;
        const ut = tv > 0 ? (vo / tv * 100).toFixed(0) + '%' : '—';
        const ch = p.priceChange?.h24 ?? null;
        const pt = detectPoolType(p);
        const chStr = ch === null ? '—' : (ch >= 0 ? '+' : '') + ch.toFixed(1) + '%';
        const chColor = ch === null ? '#999' : ch >= 0 ? '#0e7c57' : '#c0392b';
        return `<tr><td>${(p.dexId || '?').replace(/_/g, ' ')}</td><td><span style="background:${pt.color}18;color:${pt.color};border:1px solid ${pt.color}44;padding:1px 7px;border-radius:3px;font-size:7pt;font-weight:600;">${pt.type}</span></td><td class="num">${fmt(tv)}</td><td class="num">${fmt(vo)}</td><td class="num">${fmt(fe)}</td><td class="num">${ut}</td><td class="num" style="color:${chColor};">${chStr}</td></tr>`;
      }).join('');

      // Donut SVG for PDF
      const groups: Record<string, { tvl: number; color: string }> = {};
      d.pairs.forEach((p: any) => {
        const tv = parseFloat(p.liquidity?.usd || 0);
        if (tv <= 0) return;
        const pt = detectPoolType(p);
        if (!groups[pt.group]) groups[pt.group] = { tvl: 0, color: pt.color };
        groups[pt.group].tvl += tv;
      });
      const entries = Object.entries(groups).sort((a, b) => b[1].tvl - a[1].tvl);
      const sz = 180, cx = 90, cy = 90, r = 72, ri = 44;
      let angle = -Math.PI / 2, slices = '', pdfLegend = '';
      entries.forEach(([gname, { tvl, color }]) => {
        const pct = tvl / d.tvl, sweep = pct * 2 * Math.PI;
        if (sweep < 0.01) return;
        const x1 = cx + r * Math.cos(angle), y1 = cy + r * Math.sin(angle);
        const x2 = cx + r * Math.cos(angle + sweep), y2 = cy + r * Math.sin(angle + sweep);
        const xi1 = cx + ri * Math.cos(angle), yi1 = cy + ri * Math.sin(angle);
        const xi2 = cx + ri * Math.cos(angle + sweep), yi2 = cy + ri * Math.sin(angle + sweep);
        const large = sweep > Math.PI ? 1 : 0;
        slices += `<path d="M${xi1.toFixed(1)},${yi1.toFixed(1)} L${x1.toFixed(1)},${y1.toFixed(1)} A${r},${r} 0 ${large},1 ${x2.toFixed(1)},${y2.toFixed(1)} L${xi2.toFixed(1)},${yi2.toFixed(1)} A${ri},${ri} 0 ${large},0 ${xi1.toFixed(1)},${yi1.toFixed(1)} Z" fill="${color}"/>`;
        pdfLegend += `<div style="display:flex;align-items:center;gap:8px;font-size:8.5pt;"><div style="width:10px;height:10px;border-radius:3px;background:${color};flex-shrink:0;"></div><span style="flex:1;color:#333;">${gname}</span><span style="font-weight:600;color:#111;min-width:60px;text-align:right;">${fmt(tvl)}</span><span style="color:#888;min-width:40px;text-align:right;">${(pct * 100).toFixed(1)}%</span></div>`;
        angle += sweep;
      });
      const donutSVG = `<svg width="${sz}" height="${sz}" viewBox="0 0 ${sz} ${sz}">${slices}<circle cx="${cx}" cy="${cy}" r="${ri - 1}" fill="white"/><text x="${cx}" y="${cy - 7}" text-anchor="middle" fill="#111" font-size="13" font-weight="700" font-family="Inter,Helvetica,sans-serif">${fmt(d.tvl)}</text><text x="${cx}" y="${cy + 9}" text-anchor="middle" fill="#888" font-size="8" font-family="Inter,Helvetica,sans-serif" letter-spacing="0.08em">TOTAL TVL</text></svg>`;

      const cleanParas = d.paras.map((p: string) =>
        p.replace(/<strong>/g, '__BOLD__').replace(/<\/strong>/g, '__/BOLD__').replace(/<[^>]+>/g, '').replace(/__BOLD__/g, '<strong>').replace(/__\/BOLD__/g, '</strong>')
      );

      const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><title>Liquidity Audit — ${d.name} (${d.symbol})</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
*{box-sizing:border-box;margin:0;padding:0;}html,body{background:#fff;color:#111;font-family:'Inter',Helvetica,Arial,sans-serif;font-size:10pt;line-height:1.5;}
.cover{width:100%;min-height:100vh;display:flex;flex-direction:column;padding:60px 64px;page-break-after:always;}
.cover-rule{width:100%;height:2px;background:#111;margin-bottom:40px;}
.cover-eyebrow{font-size:8.5pt;letter-spacing:0.18em;text-transform:uppercase;color:#888;font-weight:500;margin-bottom:14px;}
.cover-title{font-size:34pt;font-weight:700;color:#111;line-height:1.1;margin-bottom:6px;}
.cover-sub{font-size:13pt;font-weight:300;color:#555;margin-bottom:36px;}
.cover-addr{font-size:7.5pt;font-family:'Courier New',monospace;color:#888;background:#f5f5f5;padding:8px 12px;border-radius:4px;word-break:break-all;margin-bottom:40px;display:block;}
.cover-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-bottom:36px;}
.cgi{border-top:2px solid #111;padding-top:12px;}
.cgi-l{font-size:7.5pt;letter-spacing:0.12em;text-transform:uppercase;color:#888;font-weight:500;margin-bottom:4px;}
.cgi-v{font-size:17pt;font-weight:700;color:#111;}
.cgi-s{font-size:8pt;color:#888;margin-top:2px;}
.cover-obj{padding:16px 20px;border-left:4px solid ${cfgColor};background:#f9f9f9;margin-bottom:auto;}
.cover-obj-l{font-size:7.5pt;letter-spacing:0.12em;text-transform:uppercase;color:#888;margin-bottom:4px;}
.cover-obj-v{font-size:12pt;font-weight:700;color:${cfgColor};}
.cover-footer{margin-top:36px;padding-top:14px;border-top:1px solid #e8e8e8;display:flex;justify-content:space-between;font-size:7.5pt;color:#aaa;}
.page{padding:48px 64px;page-break-before:always;}
.ph{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #ddd;padding-bottom:12px;margin-bottom:28px;}
.ph-l{font-size:8.5pt;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;}
.ph-r{font-size:8pt;color:#aaa;}
.sec{margin-bottom:28px;}
.sec-title{font-size:7.5pt;letter-spacing:0.14em;text-transform:uppercase;color:#888;font-weight:700;border-bottom:1px solid #eee;padding-bottom:7px;margin-bottom:14px;}
.mgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px;}
.mcard{padding:13px 15px;border:1px solid #e8e8e8;border-radius:5px;}
.mcard.hi{border-color:#111;background:#fafafa;}
.ml{font-size:7pt;letter-spacing:0.12em;text-transform:uppercase;color:#888;font-weight:500;margin-bottom:4px;}
.mv{font-size:17pt;font-weight:700;color:#111;line-height:1.1;}
.ms{font-size:7.5pt;color:#888;margin-top:2px;}
.arow2{display:flex;gap:18px;margin-bottom:8px;flex-wrap:wrap;}
.ai{display:flex;align-items:center;gap:6px;font-size:8.5pt;}
.adot{width:8px;height:8px;border-radius:2px;flex-shrink:0;}
.abar-out{height:8px;background:#f0f0f0;border-radius:4px;overflow:hidden;display:flex;}
.as-d{background:#1D9E75;}.as-dl{background:#378ADD;}.as-cl{background:#D85A30;}
.donut-wrap{display:flex;gap:28px;align-items:center;margin-bottom:20px;}
.pdf-leg{display:flex;flex-direction:column;gap:9px;flex:1;}
.ptable{width:100%;border-collapse:collapse;font-size:8.5pt;}
.ptable th{text-align:left;font-size:7pt;letter-spacing:0.1em;text-transform:uppercase;color:#888;font-weight:700;padding:8px 10px;border-bottom:2px solid #111;}
.ptable td{padding:9px 10px;border-bottom:1px solid #f0f0f0;color:#111;vertical-align:middle;}
.ptable tr:last-child td{border-bottom:none;}
.num{text-align:right;font-variant-numeric:tabular-nums;font-weight:500;}
.rec{background:#f9f9f9;border-left:4px solid ${cfgColor};padding:14px 18px;margin:16px 0;border-radius:0 5px 5px 0;}
.rec-l{font-size:7.5pt;letter-spacing:0.12em;text-transform:uppercase;color:${cfgColor};font-weight:700;margin-bottom:6px;}
.rec-b{font-size:9pt;color:#333;line-height:1.75;}
.asec{margin-bottom:24px;}
.asec-title{font-size:10pt;font-weight:700;color:#111;margin-bottom:10px;display:flex;align-items:center;gap:10px;}
.anum{width:22px;height:22px;border-radius:50%;background:#111;color:#fff;font-size:8pt;font-weight:700;text-align:center;line-height:22px;flex-shrink:0;}
.abody{font-size:9.5pt;line-height:1.85;color:#333;}
.abody strong{color:#111;font-weight:600;}
.disc{font-size:7pt;color:#aaa;line-height:1.6;border-top:1px solid #eee;padding-top:14px;margin-top:36px;}
@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact;}a{text-decoration:none;color:inherit;}.cover{min-height:100vh;}.page{page-break-before:always;}}
</style></head><body>
<div class="cover">
  <div style="width:100%;display:flex;align-items:center;margin-bottom:60px;">
    <div style="display:flex;align-items:center;gap:10px;">
      <div style="width:10px;height:10px;border-radius:50%;background:#1D9E75;"></div>
      <span style="font-size:11pt;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;">Liquidity Intelligence</span>
    </div>
    <span style="margin-left:auto;font-size:9pt;color:#888;">${dateStr}</span>
  </div>
  <div class="cover-rule"></div>
  <div class="cover-eyebrow">Liquidity Audit Report</div>
  <div class="cover-title">${d.name}</div>
  <div class="cover-sub">${d.symbol} &nbsp;·&nbsp; Solana Mainnet &nbsp;·&nbsp; Stage ${s.stage}: ${s.label}</div>
  <code class="cover-addr">${d.address}</code>
  <div class="cover-grid">
    <div class="cgi"><div class="cgi-l">Market Cap</div><div class="cgi-v">${fmt(d.mc)}</div><div class="cgi-s">FDV: ${fmt(d.fdv)}</div></div>
    <div class="cgi"><div class="cgi-l">Total TVL</div><div class="cgi-v">${fmt(d.tvl)}</div><div class="cgi-s">${d.pairs.length} active pool${d.pairs.length !== 1 ? 's' : ''}</div></div>
    <div class="cgi"><div class="cgi-l">Volume (24h)</div><div class="cgi-v">${fmt(d.vol24)}</div><div class="cgi-s" style="color:${priceColor};font-weight:600;">Price ${d.priceChg >= 0 ? '+' : ''}${d.priceChg.toFixed(1)}% 24h</div></div>
    <div class="cgi"><div class="cgi-l">Liquidity Ratio</div><div class="cgi-v" style="color:${lrColor};">${d.liqRatio.toFixed(1)}%</div><div class="cgi-s">${d.liqRatio < 2 ? 'Critical' : d.liqRatio < 5 ? 'Below target' : d.liqRatio > 15 ? 'Deep liquidity' : 'Healthy'}</div></div>
    <div class="cgi"><div class="cgi-l">Est. Daily Fees</div><div class="cgi-v">${fmt(d.estFees)}</div><div class="cgi-s">${d.feeDensity.toFixed(3)}% density</div></div>
    <div class="cgi"><div class="cgi-l">Volatility Regime</div><div class="cgi-v" style="font-size:13pt;">${d.vola}</div><div class="cgi-s">Inferred from 24h data</div></div>
  </div>
  <div class="cover-obj"><div class="cover-obj-l">Optimization Objective</div><div class="cover-obj-v">${cfg.label}</div></div>
  <div class="cover-footer"><span>Confidential — prepared by Dynamo Liquidity Terminal</span><span>Page 1 of 3</span></div>
</div>
<div class="page">
  <div class="ph"><span class="ph-l">${d.name} (${d.symbol}) — Metrics & Pool Inventory</span><span class="ph-r">${dateStr}</span></div>
  <div class="sec">
    <div class="sec-title">Key Performance Metrics</div>
    <div class="mgrid">
      <div class="mcard hi"><div class="ml">Token Price</div><div class="mv" style="font-size:15pt;">$${d.price.toPrecision(4)}</div><div class="ms" style="color:${priceColor};font-weight:600;">${d.priceChg >= 0 ? '+' : ''}${d.priceChg.toFixed(1)}% in 24 hours</div></div>
      <div class="mcard"><div class="ml">Market Cap</div><div class="mv">${fmt(d.mc)}</div><div class="ms">FDV: ${fmt(d.fdv)}</div></div>
      <div class="mcard"><div class="ml">Liquidity Ratio</div><div class="mv" style="color:${lrColor};">${d.liqRatio.toFixed(1)}%</div><div class="ms">${d.liqRatio < 5 ? 'Below 5% target' : d.liqRatio > 15 ? 'Deep liquidity' : 'Within healthy range'}</div></div>
      <div class="mcard"><div class="ml">Total TVL</div><div class="mv">${fmt(d.tvl)}</div><div class="ms">${d.pairs.length} active pools</div></div>
      <div class="mcard"><div class="ml">Volume (24h)</div><div class="mv">${fmt(d.vol24)}</div><div class="ms">Vol/Liq: ${d.tvl > 0 ? (d.vol24 / d.tvl).toFixed(2) : '—'}x</div></div>
      <div class="mcard"><div class="ml">Est. Daily Fees</div><div class="mv">${fmt(d.estFees)}</div><div class="ms">${d.feeDensity.toFixed(3)}% density · ${fmt(d.estFees * 365)}/yr</div></div>
    </div>
  </div>
  <div class="sec">
    <div class="sec-title">Recommended Liquidity Allocation</div>
    <div class="arow2">
      <div class="ai"><div class="adot" style="background:#1D9E75;"></div><span>DAMM Pool — ${s.damm}%</span></div>
      <div class="ai"><div class="adot" style="background:#378ADD;"></div><span>DLMM Pool — ${s.dlmm}%</span></div>
      ${s.clmm > 0 ? `<div class="ai"><div class="adot" style="background:#D85A30;"></div><span>CLMM Pool — ${s.clmm}%</span></div>` : ''}
    </div>
    <div class="abar-out"><div class="as-d" style="width:${s.damm}%;"></div><div class="as-dl" style="width:${s.dlmm}%;"></div><div class="as-cl" style="width:${s.clmm}%;"></div></div>
  </div>
  <div class="sec">
    <div class="sec-title">TVL Distribution by Pool Type</div>
    <div class="donut-wrap">${donutSVG}<div class="pdf-leg">${pdfLegend}</div></div>
  </div>
  <div class="sec">
    <div class="sec-title">Pool Inventory</div>
    <table class="ptable">
      <thead><tr><th>DEX</th><th>Type</th><th class="num">TVL</th><th class="num">Vol 24h</th><th class="num">Fees 24h</th><th class="num">Utilization</th><th class="num">24h Δ</th></tr></thead>
      <tbody>${pdfPoolRows}</tbody>
    </table>
  </div>
</div>
<div class="page">
  <div class="ph"><span class="ph-l">${d.name} (${d.symbol}) — Analysis & Recommendations</span><span class="ph-r">${dateStr}</span></div>
  <div class="rec"><div class="rec-l">Optimization Objective: ${cfg.label}</div><div class="rec-b">All recommendations in this report are calibrated for the <strong>${cfg.label}</strong> objective.</div></div>
  ${cleanParas.map((p: string, i: number) => `<div class="asec"><div class="asec-title"><span class="anum">${i + 1}</span>${sectionTitles[i] || 'Section ' + (i + 1)}</div><div class="abody">${p}</div></div>`).join('')}
  <div class="disc">This report was generated by Dynamo Liquidity Terminal on ${dateStr}. All data sourced from DexScreener. Recommendations are based on a rules-based engine calibrated to the ${cfg.label} objective. This document does not constitute financial advice.</div>
</div>
</body></html>`;

      const w2 = window.open('', '_blank');
      if (w2) { w2.document.write(html); w2.document.close(); setTimeout(() => w2.print(), 900); }
    };

    w._dynamo.goToLiveLP = () => {
      const a = lastAuditAddrRef.current;
      if (a) router.push('/livelp?addr=' + encodeURIComponent(a));
    };

    return () => {
      if (w._dynamo) {
        delete w._dynamo.setMicroCapRef;
        delete w._dynamo.exportMarkdown;
        delete w._dynamo.exportCSV;
        delete w._dynamo.exportPrint;
        delete w._dynamo.goToLiveLP;
      }
    };
  }, [router]);

  // Fill LP ownership section async after output renders
  useEffect(() => {
    if (!outputHTML || !outputRef.current) return;
    const pairs = lastAuditDataRef.current?.pairs;
    if (!pairs) return;
    const sec = outputRef.current.querySelector('#audit-lp-section');
    if (!sec) return;
    loadLPOwnershipSection(pairs).then(html => {
      if (sec) sec.innerHTML = html;
    }).catch(() => {
      if (sec) sec.innerHTML = '<div style="font-size:10px;color:#555552;padding:4px 0;">LP ownership data unavailable.</div>';
    });
  }, [outputHTML]);

  // If addr param provided, run automatically on mount
  useEffect(() => {
    const paramAddr = searchParams.get('addr');
    if (paramAddr) {
      setAddr(paramAddr);
      setTimeout(() => runAudit(paramAddr, objective), 50);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const runAudit = useCallback(async (addrOverride?: string, objOverride?: string) => {
    const targetAddr = (addrOverride || addr).trim();
    const targetObj  = objOverride || objective;
    if (!targetAddr) {
      setOutputHTML('<span class="err">Enter a token address.</span>');
      return;
    }
    setLoading(true);
    setOutputHTML('<span class="blink">Fetching from DexScreener...</span>');

    let pairs: any[] = [];
    try {
      const r = await fetch(`/api/dexscreener?address=${encodeURIComponent(targetAddr)}`);
      const d = await r.json();
      pairs = d.pairs || [];
    } catch (e: any) {
      setOutputHTML(`<span class="err">Fetch failed: ${e.message}</span>`);
      setLoading(false);
      return;
    }

    if (!pairs.length) {
      setOutputHTML('<span class="err">No pools found. Use the token mint address, not the pair address.</span>');
      setLoading(false);
      return;
    }

    const ti = pairs[0].baseToken || {};
    const price = parseFloat(pairs[0].priceUsd) || 0;
    const mc    = parseFloat(pairs[0].marketCap) || 0;
    const fdv   = parseFloat(pairs[0].fdv) || mc;
    let tvl = 0, vol24 = 0;
    pairs.forEach((p: any) => { tvl += parseFloat(p.liquidity?.usd || 0); vol24 += parseFloat(p.volume?.h24 || 0); });
    const liqRatio = tvl > 0 && mc > 0 ? tvl / mc * 100 : 0;
    const volLiq   = tvl > 0 ? vol24 / tvl : 0;
    const priceChg = parseFloat(pairs[0]?.priceChange?.h24 || 0);
    const avgChg   = pairs.slice(0, 5).reduce((a: number, p: any) => a + Math.abs(parseFloat(p.priceChange?.h24 || 0)), 0) / Math.min(pairs.length, 5);
    const vola     = avgChg > 20 ? 'Extreme' : avgChg > 10 ? 'High' : avgChg > 5 ? 'Medium' : 'Low';
    const s        = classifyStage(mc);
    const c        = sc(s.stage);
    const estFees  = vol24 * 0.003;
    const feeDensity = tvl > 0 ? estFees / tvl * 100 : 0;
    const cfg = objConfig(targetObj);
    const sh  = getShape(vola, 1.0, targetObj);
    const rwv = getRW(vola, targetObj);
    let recDamm = s.damm, recDlmm = s.dlmm, recClmm = s.clmm;
    if (targetObj === 'fee')       { recDlmm = Math.min(100, recDlmm + 10); recDamm = Math.max(0, recDamm - 10); }
    if (targetObj === 'stability') { recDamm = Math.min(100, recDamm + 10); recDlmm = Math.max(0, recDlmm - 10); }

    const poolRows = buildPoolRows(pairs);
    const donut    = buildDonutChart(pairs, tvl);
    const paras    = auditAnalysis({ name: ti.name || 'Unknown', symbol: ti.symbol || '?', mc, fdv, tvl, vol24, liqRatio, volLiq, pairs, priceChg, vola, stage: s.stage }, targetObj);
    const slipData = [500, 1000, 5000, 10000].map(sz => {
      const imp = estSlippage(sz, pairs);
      return { sz, imp, col: imp < 0.5 ? '#1D9E75' : imp < 1 ? '#BA7517' : imp < 3 ? '#D85A30' : '#c94a4a', lbl: imp < 0.5 ? 'Excellent' : imp < 1 ? 'Acceptable' : imp < 3 ? 'High' : 'Very high' };
    });
    const microCapHTML  = buildMicroCapSection(mc, volLiq, tvl);
    const fragScore     = calcFragScore(pairs);
    const fragLabel     = fragScore >= 75 ? 'Healthy' : fragScore >= 50 ? 'Moderate' : fragScore >= 25 ? 'Fragmented' : 'Severely Fragmented';
    const fragColor     = fragScore >= 75 ? '#1D9E75' : fragScore >= 50 ? '#BA7517' : fragScore >= 25 ? '#D85A30' : '#c94a4a';
    const domTVL        = pairs.reduce((mx: number, p: any) => Math.max(mx, parseFloat(p.liquidity?.usd || 0)), 0);
    const domPct        = tvl > 0 ? (domTVL / tvl * 100) : 0;
    const fragExpl      = `Largest pool holds ${domPct.toFixed(0)}% of TVL across ${pairs.length} pool${pairs.length !== 1 ? 's' : ''}.`;
    const fragNote      = fragScore >= 75 ? 'Concentration is healthy — routing is competitive and fee density is near-optimal.'
      : fragScore >= 50 ? `Moderate spread. Consolidating the ${pairs.length - 1} smaller pools into the primary would improve both routing and fee density.`
      : fragScore >= 25 ? `TVL is spread across ${pairs.length} pools with no dominant position. No single pool has sufficient depth to win Jupiter routing at most trade sizes — consolidation is overdue.`
      : `Severe fragmentation across ${pairs.length} pools. This structure is actively losing volume to better-structured tokens. Consolidation is the single highest-impact action available.`;
    const routingScore  = calcRoutingScore(pairs, tvl, mc);
    const routingLabel  = routingScore >= 70 ? 'Dominant' : routingScore >= 45 ? 'Competitive' : routingScore >= 20 ? 'Weak' : 'Non-competitive';
    const routingColor  = routingScore >= 70 ? '#1D9E75' : routingScore >= 45 ? '#BA7517' : routingScore >= 20 ? '#D85A30' : '#c94a4a';
    const rMedianTrade  = mc < 250000 ? 200 : mc < 1000000 ? 750 : mc < 5000000 ? 2500 : 7500;
    const rDepthNeeded  = rMedianTrade * 100;
    const rBestTVL      = pairs.reduce((mx: number, p: any) => Math.max(mx, parseFloat(p.liquidity?.usd || 0)), 0);
    const rDepthGap     = Math.max(0, rDepthNeeded - rBestTVL);
    const rBestPool     = pairs.reduce((mx: any, p: any) => parseFloat(p.liquidity?.usd || 0) > parseFloat(mx.liquidity?.usd || 0) ? p : mx, pairs[0]);
    const rBestPT       = detectPoolType(rBestPool);
    const rDepthRatio   = rBestTVL / (rDepthNeeded || 1);
    const routingFactors = [
      `Depth: ${fmt(rBestTVL)} in largest pool vs ${fmt(rDepthNeeded)} target for &lt;0.5% slippage at $${rMedianTrade.toLocaleString()} median trade — ${rDepthRatio >= 1 ? '<span style="color:#1D9E75;">sufficient</span>' : `<span style="color:#c94a4a;">deficit of ${fmt(rDepthGap)}</span>`}.`,
      `Fragmentation: ${fragScore}/100 — ${fragScore >= 75 ? 'concentrated, favours routing' : 'fragmented, hurts routing'}.`,
      `Venue: dominant pool is <strong style="color:#e8e8e6;">${rBestPT.type}</strong> on <strong style="color:#e8e8e6;">${(rBestPool?.dexId || 'unknown').replace(/_/g, ' ')}</strong> — ${rBestPT.group === 'Meteora DLMM' ? '<span style="color:#1D9E75;">optimal for Jupiter routing</span>' : '<span style="color:#BA7517;">Meteora DLMM scores higher</span>'}.`,
    ];
    const routingAction = routingScore >= 70
      ? 'Maintain this structure — the primary risk is TVL withdrawal or a new competing pool fragmenting the dominant position.'
      : routingScore >= 45
      ? (rDepthGap > 0 ? `Closing the ${fmt(rDepthGap)} depth gap in the primary pool would push the score into Dominant.` : `Depth is sufficient — the routing limiter is ${fragScore < 50 ? 'pool fragmentation; consolidate into one dominant position' : 'venue; migrating the primary pool to Meteora DLMM would improve route scoring'}.`)
      : routingScore >= 20
      ? `Two changes: ${pairs.length > 3 ? 'consolidate fragmented pools into one dominant position, and ' : ''}${rBestPT.group !== 'Meteora DLMM' ? 'migrate primary liquidity to Meteora DLMM for optimal routing' : 'add ' + fmt(rDepthGap) + ' to primary pool depth to hit the slippage target'}.`
      : `Not competing for Jupiter routing at current structure. Build a single concentrated Meteora DLMM targeting ${fmt(rDepthNeeded)} depth as the starting point.`;

    // Store for export and micro-cap
    lastAuditDataRef.current = { address: targetAddr, name: ti.name || 'Unknown', symbol: ti.symbol || '?', price, mc, fdv, tvl, vol24, liqRatio, volLiq, priceChg, vola, estFees, feeDensity, stage: s, pairs, objective: targetObj, paras };
    lastAuditAddrRef.current = targetAddr;
    if (mc < 40000) {
      microCapParamsRef.current = { mc, volLiq, tvl, ref: 1000 };
    } else {
      microCapParamsRef.current = null;
    }

    const riskHTML = buildRiskSection(mc, fdv, tvl, vol24, liqRatio, volLiq, priceChg, pairs);

    const html = `${riskHTML}
    <div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px;margin-bottom:4px;">
      <div>
        <span style="font-size:14px;font-weight:500;color:#e8e8e6;">${ti.name || 'Unknown'}</span>
        <span style="color:#555552;font-size:11px;margin-left:6px;">${ti.symbol || '?'}</span>
        <span style="margin-left:8px;background:${cfg.color}18;color:${cfg.color};border:0.5px solid ${cfg.color}44;border-radius:4px;padding:1px 8px;font-size:10px;">${cfg.label}</span>
      </div>
      <div class="export-bar" style="margin-bottom:0;">
        <button class="export-btn" onclick="window._dynamo&&window._dynamo.goToLiveLP()">→ Live LP</button>
        <button class="export-btn" onclick="window._dynamo&&window._dynamo.exportMarkdown()">↓ Markdown</button>
        <button class="export-btn" onclick="window._dynamo&&window._dynamo.exportCSV()">↓ CSV</button>
        <button class="export-btn" onclick="window._dynamo&&window._dynamo.exportPrint()">⎙ Print / PDF</button>
      </div>
    </div>
    <div style="font-size:10px;color:#555552;margin-bottom:14px;word-break:break-all;">${targetAddr}</div>
    <div class="mrow">
      <div class="mc2"><div class="ml">Price</div><div class="mv">${price > 0 ? '$' + price.toPrecision(4) : '—'}</div><div class="ms" style="color:${priceChg >= 0 ? '#1D9E75' : '#c94a4a'};">${priceChg >= 0 ? '+' : ''}${priceChg.toFixed(1)}% 24h</div></div>
      <div class="mc2"><div class="ml">Market Cap</div><div class="mv">${fmt(mc)}</div></div>
      <div class="mc2"><div class="ml">Total TVL</div><div class="mv">${fmt(tvl)}</div></div>
      <div class="mc2"><div class="ml">Vol 24h</div><div class="mv">${fmt(vol24)}</div></div>
      <div class="mc2"><div class="ml">Liq Ratio</div><div class="mv">${liqRatio.toFixed(1)}%</div><div class="ms">${liqRatio < 2 ? '⚠ critical' : liqRatio < 5 ? '⚠ thin' : liqRatio > 15 ? '↑ deep' : '✓ healthy'}</div></div>
      <div class="mc2"><div class="ml">Est. Daily Fees</div><div class="mv">${fmt(estFees)}</div></div>
    </div>
    <div onclick="this.nextElementSibling.style.display=this.nextElementSibling.style.display==='grid'?'none':'grid';this.querySelector('.dtgl').textContent=this.nextElementSibling.style.display==='grid'?'▾':'▸';" style="cursor:pointer;display:flex;align-items:center;gap:5px;font-size:10px;color:#444442;margin-bottom:8px;user-select:none;">
      <span class="dtgl">▸</span>
      <span>FDV ${fmt(fdv)} · ${pairs.length} pool${pairs.length !== 1 ? 's' : ''} · ${vola} volatility · ${feeDensity.toFixed(3)}% fee density</span>
    </div>
    <div style="display:none;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:5px;margin-bottom:10px;">
      <div style="background:#0f0f0f;border:0.5px solid rgba(255,255,255,0.06);border-radius:4px;padding:5px 8px;"><div style="font-size:8px;color:#444442;text-transform:uppercase;letter-spacing:0.07em;margin-bottom:2px;">FDV</div><div style="font-size:12px;color:#888884;">${fmt(fdv)}</div></div>
      <div style="background:#0f0f0f;border:0.5px solid rgba(255,255,255,0.06);border-radius:4px;padding:5px 8px;"><div style="font-size:8px;color:#444442;text-transform:uppercase;letter-spacing:0.07em;margin-bottom:2px;">Pools</div><div style="font-size:12px;color:#888884;">${pairs.length}</div></div>
      <div style="background:#0f0f0f;border:0.5px solid rgba(255,255,255,0.06);border-radius:4px;padding:5px 8px;"><div style="font-size:8px;color:#444442;text-transform:uppercase;letter-spacing:0.07em;margin-bottom:2px;">Volatility</div><div style="font-size:12px;color:#888884;">${vola}</div></div>
      <div style="background:#0f0f0f;border:0.5px solid rgba(255,255,255,0.06);border-radius:4px;padding:5px 8px;"><div style="font-size:8px;color:#444442;text-transform:uppercase;letter-spacing:0.07em;margin-bottom:2px;">Fee Density</div><div style="font-size:12px;color:#888884;">${feeDensity.toFixed(3)}%</div></div>
    </div>
    <div style="display:flex;align-items:center;gap:10px;margin-bottom:10px;flex-wrap:wrap;">
      <span class="badge" style="background:${c}22;color:${c};border:0.5px solid ${c}44;">Stage ${s.stage}: ${s.label}</span>
    </div>
    <div class="lrow">
      <span class="ldot" style="background:#1D9E75;"></span><span class="llbl">DAMM ${recDamm}% rec.</span>
      <span class="ldot" style="background:#378ADD;"></span><span class="llbl">DLMM ${recDlmm}% rec.</span>
      <span class="ldot" style="background:#D85A30;"></span><span class="llbl">CLMM ${recClmm}% rec.</span>
    </div>
    <div class="abar"><div class="fd" style="width:${recDamm}%"></div><div class="fdl" style="width:${recDlmm}%"></div><div class="fcl" style="width:${recClmm}%"></div></div>
    <div style="font-size:11px;color:#888884;margin:8px 0 14px;">Rec. shape: <span style="color:#e8e8e6;">${sh}</span> · Range: <span style="color:#e8e8e6;">${rwv}</span> · <span style="color:#e8e8e6;">${getBinConfig(mc, targetObj).desc}</span> · Treasury LP: <span style="color:#e8e8e6;">${getTLP(s.stage)}</span></div>

    <div class="sl">TVL by pool type</div>
    ${donut}

    <div class="sl">Pool inventory</div>
    <div class="pool-wrap">
      <div class="ph"><span style="min-width:110px;">DEX</span><span style="min-width:90px;">Type</span><span style="min-width:75px;">TVL</span><span style="min-width:75px;">Vol 24h</span><span style="min-width:65px;">Fees 24h</span><span style="min-width:50px;">Util</span><span style="min-width:60px;">24h Δ</span><span>Links</span></div>
      ${poolRows}
    </div>

    <div class="sl">Slippage estimator</div>
    <div class="mrow" style="margin-bottom:4px;">
      ${slipData.map(d => `<div class="mc2"><div class="ml">$${d.sz >= 1000 ? d.sz / 1000 + 'k' : d.sz} trade</div><div class="mv" style="color:${d.col};">${d.imp < 0.1 ? '<0.1' : d.imp.toFixed(2)}%</div><div class="ms" style="color:${d.col};">${d.lbl}</div></div>`).join('')}
    </div>
    <div style="font-size:10px;color:#555552;margin-bottom:16px;">Estimated against the deepest single pool using pool type concentration factors. Actual impact depends on active bin depth — treat as directional.</div>

    ${microCapHTML}

    <div class="sl">Fragmentation score</div>
    <div style="border:0.5px solid rgba(255,255,255,0.08);border-radius:6px;background:#0f0f0f;padding:14px 16px;margin-bottom:16px;">
      <div style="display:flex;align-items:center;gap:14px;margin-bottom:10px;flex-wrap:wrap;">
        <div style="display:flex;align-items:baseline;gap:5px;">
          <span style="font-size:28px;font-weight:600;color:${fragColor};">${fragScore}</span>
          <span style="font-size:11px;color:#555552;">/100</span>
        </div>
        <span class="badge" style="background:${fragColor}22;color:${fragColor};border:0.5px solid ${fragColor}44;">${fragLabel}</span>
        <div style="flex:1;min-width:100px;">
          <div style="height:4px;border-radius:2px;background:#1e1e1e;overflow:hidden;">
            <div style="height:100%;width:${fragScore}%;background:${fragColor};border-radius:2px;transition:width .3s;"></div>
          </div>
        </div>
      </div>
      <div style="font-size:11px;color:#555552;margin-bottom:6px;">${fragExpl}</div>
      <div style="font-size:12px;color:#888884;line-height:1.7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">${fragNote}</div>
    </div>

    <div class="sl">Routing dominance score</div>
    <div style="border:0.5px solid rgba(255,255,255,0.08);border-radius:6px;background:#0f0f0f;padding:14px 16px;margin-bottom:16px;">
      <div style="display:flex;align-items:center;gap:14px;margin-bottom:12px;flex-wrap:wrap;">
        <div style="display:flex;align-items:baseline;gap:5px;">
          <span style="font-size:28px;font-weight:600;color:${routingColor};">${routingScore}</span>
          <span style="font-size:11px;color:#555552;">/100</span>
        </div>
        <span class="badge" style="background:${routingColor}22;color:${routingColor};border:0.5px solid ${routingColor}44;">${routingLabel}</span>
        <div style="flex:1;min-width:100px;">
          <div style="height:4px;border-radius:2px;background:#1e1e1e;overflow:hidden;">
            <div style="height:100%;width:${routingScore}%;background:${routingColor};border-radius:2px;"></div>
          </div>
        </div>
      </div>
      <div style="display:flex;flex-direction:column;gap:5px;margin-bottom:12px;">
        ${routingFactors.map(f => `<div style="display:flex;gap:8px;font-size:11px;color:#555552;line-height:1.6;"><span style="color:#333;flex-shrink:0;">·</span><span>${f}</span></div>`).join('')}
      </div>
      <div style="font-size:12px;color:#888884;line-height:1.7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;border-top:0.5px solid rgba(255,255,255,0.06);padding-top:10px;">${routingAction}</div>
    </div>

    <div id="audit-lp-section"><div style="padding:8px 0;font-size:10px;color:#333;"><span class="blink">Loading LP ownership data…</span></div></div>

    <div class="analysis">
      <div class="analysis-label">◈ Audit analysis &nbsp;<span class="obj-tag" style="background:${cfg.color}18;color:${cfg.color};border:0.5px solid ${cfg.color}44;padding:1px 8px;border-radius:10px;">${cfg.label} objective</span></div>
      ${paras.map(p => `<p>${p}</p>`).join('')}
    </div>`;

    setOutputHTML(html);
    setLoading(false);
  }, [addr, objective]);

  const objButtons = [
    { key: 'fee',       label: '⬡ Fee Generation'  },
    { key: 'stability', label: '◈ Price Stability'  },
    { key: 'volume',    label: '↑ Volume Growth'    },
    { key: 'balanced',  label: '⊕ Balanced'         },
  ];

  return (
    <div style={{ padding: '16px' }}>
      <div className="sl">Token mint address</div>
      <div className="arow">
        <input
          value={addr}
          onChange={e => setAddr(e.target.value)}
          onKeyDown={e => { if (e.key === 'Enter') runAudit(); }}
          placeholder="e.g. oreoU2P8bN6jkk3jbaiVxYnG1dCXcYxwhwyK9jSybcp"
        />
        <button className="rbtn" style={{ marginBottom: 0 }} onClick={() => runAudit()} disabled={loading}>
          ⊕ Audit
        </button>
      </div>
      <div className="hint">Token mint address only — not the pair address.</div>

      <div className="sl" style={{ marginTop: 12 }}>Optimization objective</div>
      <div className="obj-row">
        {objButtons.map(ob => (
          <button
            key={ob.key}
            className={`obj-btn ${ob.key}${objective === ob.key ? ' active' : ''}`}
            onClick={() => setObjective(ob.key)}
          >
            {ob.label}
          </button>
        ))}
      </div>

      <div className="out" ref={outputRef}>
        {outputHTML
          ? <div dangerouslySetInnerHTML={{ __html: outputHTML }} />
          : <span className="ph2">Enter a token address, select your optimization objective, then audit.</span>
        }
      </div>
    </div>
  );
}
